version: '2'

services:
  ccc:
    image: "cloud-compute-cannon:latest"
    command: ["${EXECUTABLE}", "build/test/compute_tests.js"]
    volumes:
      - ./:/config
      - ./test:/app/test
      - ./build:/app/build
    environment:
      AWS: "false"
      DOCKER: "true"
      VAGRANT: "false"

  redis:
    logging:
      driver: "none"
      options: {}

  registry:
    logging:
      driver: "none"
      options: {}

  fluentd:
    image: fluent/fluentd:v0.14.2
    volumes:
      - ./etc/log/fluent.prod.conf:/fluentd/etc/fluent.conf
    logging:
      driver: none