compute:
  extends:
    file: docker-compose.core.yml
    service: compute
  links:
    - redis
    - registry:registry.host


redis:
  extends:
    file: docker-compose.core.yml
    service: redis


registry:
  extends:
    file: docker-compose.core.yml
    service: registry

