version: '2'

services:

  compile-lambda:
    image: dionjwa/haxe-watch:v0.7.3
    command: ["haxe", "etc/bionano/aws/cloudformation/lambda-autoscaling/src/build.hxml"]
    working_dir: /app
    volumes:
      - ./build:/app/build
      - ./.haxelib:/app/.haxelib
      - ./src:/app/src
      - ./etc:/app/etc
      - ./clients:/app/clients
