compute:
  extends:
    file: docker-compose.core.yml
    service: compute
  command: ["node", "build/server/cloud-compute-cannon-server.js"]
  links:
    - redis
  environment:
    TRAVIS: "${TRAVIS}"
  volumes:
    - ./data:/app/data
    # - ./build:/app/build
  log_driver: "json-file"
  log_opt: {}

redis:
  extends:
    file: docker-compose.core.yml
    service: redis
  log_driver: "json-file"
  log_opt: {}
