version: '2'

services:

  compute:
    image: "quay.io/bionano/cloud-compute-cannon:${VERSION}"
    command: ["forever", "server/cloud-compute-cannon-server.js"]
    volumes:
      - ./:/app/config/
    environment:
      LOG_LEVEL: "${LOG_LEVEL}"
      CONFIG_PATH: "/app/config/ccc.yml"
      CLIENT_DEPLOYMENT: "true"
    logging:
      driver: json-file

  redis:
    volumes:
      - ./etc/redis/redis-prod.conf:/usr/local/etc/redis/redis.conf
    logging:
      driver: "fluentd"
      options:
        tag: "docker.ccc{{.ImageName}}/{{.ID}}"
        fluentd-address: "localhost:24225"

  registry:
    #TODO: use a more sophisticated cleanup mechanism, and use redis?
    environment:
      SETTINGS_FLAVOR: local
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        tag: "docker.ccc{{.ImageName}}/{{.ID}}"
        fluentd-address: "localhost:24225"

  fluentd:
    image: fluent/fluentd:v0.14.2
    volumes:
      - ./etc/log/fluent.prod.conf:/fluentd/etc/fluent.conf
    logging:
      driver: json-file