version: '2'

services:

  # nginx:
  #   image: "nginx:1.10-alpine"
  #   ports: #"HOST:CONTAINER"
  #     - "9000:80"
  #   volumes:
  #     - ./etc/nginx/nginx.conf.dev:/etc/nginx/conf.d/default.conf
  #   links:
  #     - ccc1
  #     # - ccc2
  #     # - ccc3

  ccc1:
    extends:
      file: "docker-compose.dev-server-local-base.yml"
      service: "ccc"
    ports:
      - "9001:9000"
    links:
      - redis1
      # - fluentd

  # ccc2:
  #   extends:
  #     file: "docker-compose.dev-server-local-base.yml"
  #     service: "ccc"
  #   ports:
  #     - "9010:9000"
  #   links:
  #     - redis1

  # ccc3:
  #   extends:
  #     file: "docker-compose.dev-server-local-base.yml"
  #     service: "ccc"
  #   ports:
  #     - "9020:9000"
  #   links:
  #     - redis1

  bull-ui-server:
    build:
      context:
        "etc/bull-ui-server/"
    environment:
      PORT: "9002"
      REDIS_HOST: 'redis1'
    ports: #"HOST:CONTAINER"
      - "9002:9002"
    links:
      - redis1

  redis1:
    restart: always
    image: redis:3.2.0-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - ./etc/redis/redis-dev.conf:/usr/local/etc/redis/redis.conf
    # logging:
    #   driver: none

  # fluentd:
  #   build: ./etc/log/
  #   volumes:
  #     - ./etc/log/fluent.dev.conf:/fluentd/etc/fluent.conf
  #   links:
  #     - elasticsearch
  #   logging:
  #     driver: none

  # elasticsearch:
  #   extends:
  #     file: docker-compose.core.yml
  #     service: elasticsearch
  #   logging:
  #     driver: none

  # kibana:
  #   extends:
  #     file: docker-compose.core.yml
  #     service: kibana
  #   links:
  #     - elasticsearch
