version: '2'

services:

  ccc:
    restart: "always"
    image: "quay.io/bionano/cloud-compute-cannon:${VERSION}"
    volumes:
      - ./:/app/config/
    environment:
      LOG_LEVEL: "${LOG_LEVEL}"
      CONFIG_PATH: "/app/config/ccc.yml"
      CLIENT_DEPLOYMENT: "true"
      FLUENT_PORT: "24226"
    logging:
      driver: json-file
      options:
        max-size: 50m

  redis:
    volumes:
      - ./etc/redis/redis-prod.conf:/usr/local/etc/redis/redis.conf
    logging:
      driver: "fluentd"
      options:
        tag: "docker.ccc{{.ImageName}}/{{.ID}}"
        fluentd-address: "${BNR_INSTANCE_IP}:24226"