version: '2'

services:
  ccc:
    extends:
      file: "docker-compose.yml"
      service: "ccc"
    image: "cloud-compute-cannon:latest"
    command: ["${EXECUTABLE}", "build/test/compute_tests.js"]
    volumes:
      - ./:/config
      - ./test:/app/test
      - ./build:/app/build
    environment:
      AWS: "false"
      DOCKER: "true"
      VAGRANT: "false"
      REDIS_HOST: "redis1"
      SCALE_UP_CONTROL: "external"
      SCALE_DOWN_CONTROL: "external"
      ENABLE_FLUENT: "false"

  redis1:
    extends:
      file: "docker-compose.dev-server-local-base.yml"
      service: "ccc"
    logging:
      driver: "none"
      options: {}
