version: '2'

services:

  ccc:
    extends:
      file: docker-compose.core.yml
      service: ccc
    image: "quay.io/bionano/cloud-compute-cannon:e0d23cc2"
    command: ["nodemon", "-w", "server", "-w", "/app/config/ccc.yml", "server/cloud-compute-cannon-server.js"]
    volumes:
      - ./build/server:/app/server
      - ./src/web:/app/web
      - ./:/app/config
    environment:
      LOG_LEVEL: "10"
      CONFIG_PATH: "/app/config/ccc.yml"
      PORT: "9000"
      REDIS_HOST: 'redis'
      CLIENT_DEPLOYMENT: "true"
      SCALE_UP_CONTROL: "external"
      SCALE_DOWN_CONTROL: "external"
      ENABLE_FLUENT: "true"
    links:
      - redis
      - fluentd
    logging:
      driver: json-file

  redis:
    extends:
      file: docker-compose.core.yml
      service: redis
    volumes:
      - ./etc/redis/redis-dev.conf:/usr/local/etc/redis/redis.conf
    ports:
      #Don't expose this port to the host, only linked containers.
      - "6379:6379"

  fluentd:
    build: ./etc/log/
    volumes:
      - ./etc/log/fluent.dev.conf:/fluentd/etc/fluent.conf
    links:
      - elasticsearch
    logging:
      driver: none

  elasticsearch:
    extends:
      file: docker-compose.core.yml
      service: elasticsearch
    logging:
      driver: none

  kibana:
    extends:
      file: docker-compose.core.yml
      service: kibana
    links:
      - elasticsearch
