compute:
  command: ["haxe", "test/testsIntegration.hxml"]
  environment:
    AWS: "true"
    DOCKER: "false"
    VAGRANT: "false"
  log_driver: "json-file"
  log_opt: {}

# redis:
#   log_driver: "none"

registry:
  log_driver: "none"

elasticsearch:
  log_driver: "none"

kibana:
  log_driver: "none"