version: '2'

volumes:
  redis-data:
    driver: local
  ccc-local-storage:
    driver: local

services:

  serverworker:
    image: quay.io/bionano/cloud-compute-cannon:dd574008
    cpu_shares: 1024
    ports:
      - "9090:9000"
    links:
      - redis
    working_dir: /app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ccc-local-storage:/app/ccc-local-storage
    environment:
      - PORT=9000
      - STORAGE_HTTP_PREFIX=http://ccc.local
      - REDIS_HOST=redis
      - LOG_LEVEL=info

  redis:
    cpu_shares: 256
    image: redis:3.2.0-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./etc/redis/redis-dev.conf:/usr/local/etc/redis/redis.conf
    logging:
      driver: none
