version: '2'

services:
  ccc:
    command: ["haxe", "test/testsIntegration.hxml"]
    environment:
      AWS: "true"
      DOCKER: "false"
      VAGRANT: "false"
    logging:
      driver: "json-file"
      options: {}

  redis:
    logging:
      driver: "json-file"
      options: {}

  elasticsearch:
    logging:
      driver: "none"
      options: {}

  kibana:
    logging:
      driver: "none"
      options: {}