version: '2'

volumes:
  redis-data:
    driver: local
  ccc-local-storage:
    driver: local

services:
  ccc:
    extends:
      file: docker-compose.core.yml
      service: ccc
    links:
      - redis
      - fluentd

  redis:
    extends:
      file: docker-compose.core.yml
      service: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./etc/redis/redis-prod.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
    links:
      - fluentd

  fluentd:
    extends:
      file: docker-compose.core.yml
      service: fluentd