version: '2'

services:

  ccc:
    environment:
      PORT: "9000"
      # OPTIONAL: Path to the mounted configuration file
      # CONFIG_PATH: "/app/ccc.yml"
      # OPTIONAL text flattened yaml of the server configuration.
      # COMPUTE_CONFIG: "${COMPUTE_CONFIG}"
      #This is used to get the correct host working directory to pass into the
      #worker containers to map the local file system to /inputs+/outputs within
      #the container. Only used for local docker providers (not cloud)
      HOST_PWD: "$PWD"
      STORAGE_HTTP_PREFIX: 'http://localhost:9000/'
      REDIS_HOST: 'redis1'

      # CONFIG_PATH: "/app/config/ccc.yml"
      CLIENT_DEPLOYMENT: "false"
      SCALE_UP_CONTROL: "external"
      SCALE_DOWN_CONTROL: "external"
      ENABLE_FLUENT: "false"
      LOCAL: "true"

    image: "quay.io/bionano/cloud-compute-cannon:7a5cc7d8"
    # command: ["nodemon", "-w", "server", "server/cloud-compute-cannon-server.js"]
    command: ["nodemon", "--inspect", "--debug-brk", "server/cloud-compute-cannon-server.js"]
    # command: ["echo", "server/cloud-compute-cannon-server.json"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./build/server:/app/server
      - ./clients/dashboard/build:/app/clients/dashboard
      - ./src/web:/app/web
      - ./ccc-local-storage:/app/ccc-local-storage
      - ./package.json:/app/package.json
      # - ./:/app/config
    logging:
      driver: json-file
