compute:
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    #Mount local storage, even though it might use S3, we don't know at this point.
    - ./data/computejobs:/computejobs
    - ./data:/app/data
    - ./:/config
  links:
    - redis
    - registry
    - fluentd
  environment:
    CLIENT_DEPLOYMENT: "true"


redis:
  command: redis-server /usr/local/etc/redis/redis.conf
  volumes:
    - ./etc/redis/redis-prod.conf:/usr/local/etc/redis/redis.conf
    # This is the where the db will be writting. It is defined in ./etc/redis/redis-prod.conf
    - ./data/redis:/data
  ports:
    #Don't expose this port to the host, only linked containers.
    - "6379"


registry:
  volumes:
    #Always persist the registry locally. This makes it easier to clean.
    - ./data/registry:/var/lib/registry
  #TODO: use a more sophisticated cleanup mechanism, and use redis?
  environment:
    SETTINGS_FLAVOR: local
    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
  links:
    - fluentd


fluentd:
  build: ./etc/log/
  volumes:
    - ./etc/log/fluent.prod.conf:/fluentd/etc/fluent.conf
  links:
    - elasticsearch


elasticsearch:
  extends:
    file: docker-compose.core.yml
    service: elasticsearch
  log_driver: "json-file"
  log_opt: {}


kibana:
  extends:
    file: docker-compose.core.yml
    service: kibana
  links:
    - elasticsearch