compute:
  command: ["haxe", "test/testsIntegration.hxml"]
  environment:
    AWS: "false"
    DOCKER: "true"
    VAGRANT: "false"

fluentd:
  log_driver: "none"

redis:
  log_driver: "none"

registry:
  log_driver: "none"

elasticsearch:
  log_driver: "none"

kibana:
  log_driver: "none"