version: '2'

services:

  ccc:
    restart: "always"
    image: "quay.io/bionano/cloud-compute-cannon:${VERSION}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/app/config/
    ports:
      - "9000:9000"
    environment:
      CLOUD_PROVIDER_TYPE: "aws"
      PORT: "9000"
      REDIS_HOST: "redis-ccc.${BNR_ENVIRONMENT}.bionano.bio"
      CONFIG_PATH: "/app/config/ccc.yml"
      FLUENT_HOST: "fluentd"
      FLUENT_PORT: "24226"
      LOG_LEVEL: "info"
    extra_hosts:
      # in aws remove 'fluentd' container and add the same name into host file with ip of host, which is running fluent server (td-agent)
      - "fluentd:${BNR_INSTANCE_IP}"
