version: '2'

volumes:
  ccc-local-storage:
    driver: local

services:

  ccc:
    restart: 'always'
    image: 'quay.io/bionano/cloud-compute-cannon:507d8cd6'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ccc-local-storage:/app/ccc-local-storage
    environment:
      LOG_LEVEL: '10'
      ENABLE_FLUENT: 'false'
      HOST_PWD: '$PWD'
      PORT: '9000'
    ports:
      - '9000:9000'
    links:
      - redis

  redis:
    restart: always
    image: redis:3.2.0-alpine
    ports:
      - '6379'


