storage:
  type: "local"
  rootPath: "ccc_local_storage"

providers:
  - type: "Vagrant"
    priority: 1
    maxWorkers: 4
    minWorkers: 0
    #billingIncrement is measured in minutes
    billingIncrement: 0
    vagrantRootPath: ./tmp/vagrantWorkerProvider