storage:
    type: "local"
    rootPath: "data/ServiceStorageLocalFileSystem"

providers:
  - type: "Vagrant"
    priority: 1
    maxWorkers: 4
    minWorkers: 0
    #billingIncrement is measured in minutes
    billingIncrement: 0
    vagrantRootPath: ./tmp/vagrantWorkerProvider