storage:
  type: "local"
  rootPath: "ccc_local_storage"

providers:
  - type: "Boot2Docker"
    maxWorkers: 1
    minWorkers: 1
    priority: 1
    #billingIncrement is measured in minutes
    billingIncrement: 0
